const recommendedProductName = 'test'

intent('hi1',(p)=>{                
    const popupTemplate = p.createPopup({
        json: {foo:'123'},  
        name: "test1",  
        exampleRequest: "Say Find Tito's Vodka",
        style:".rover-animation{height:200px;width:200px;margin-top:-51px}.info-popup{background:linear-gradient(.45turn,#efefef,#fff);max-width:394px;height:280px;width:400px;max-height:280px;-webkit-box-shadow:0 5px 14px rgba(0,0,0,.25);box-shadow:0 5px 14px rgba(0,0,0,.25);overflow:hidden;border-radius:10px;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column}.info-popup_header{padding-left:15px;display:flex;height:193px;width:100%;color:#000;font-size:22px;font-weight:700;padding-top:48px;padding-right:10px;text-align:center;background:linear-gradient(102.76deg,#fbf7f7 2.32%,#e0e4e9 94.85%);background-repeat:no-repeat;background-position:center center;background-size:100% 100%}.info-popup_body{display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;font-weight:400;font-size:23px;line-height:48px;text-align:center;color:#000;padding:9px ​50px;height:89px}.info-popup_pointer-button{margin:22px auto 10px}.grey-arrow{font-family:Arial,Helvetica,sans-serif;width:253px;height:42px;line-height:42px;font-weight:700;font-size:18px;text-align:center;margin-left:50px;background-image:url(https://storage.googleapis.com/alan-public-images/rover_grey_arrow.svg);background-repeat:no-repeat;background-size:100% auto}.alan-overlay-popup__ok{background:none; opacity:0.3; color:#000}.alan-overlay-popup__ok:before{content:'✕';position: absolute;top:0;left:0;width:100%;height:100%;font-size:18px;color:#bfbfbf; opacity:1 !important}",
        html: `111<div class="info-popup"> <div class="info-popup_header" style="font-size: 21px;"><object type="image/svg+xml" class="rover-animation" alt="triangle with all three sides equal"/></object><span style="display: contents;">Say</span> </br> <span style="font-size:19px; color:#EA1D2D; font-weight:800; display: contents;">"Find Tito\'s Vodka"</span> </div><div class="info-popup_body"> <div class="info-popup_pointer-button grey-arrow" style="font-size: 13px;">You can get free delivery!</div></div></div>`,
    });                 
})         




intent('hi2',(p)=>{                
   const popup = p.createPopup({
        name: "test2",
        exampleRequest: "Say Find Tito\'s Vodka",
        style:".rover-animation{height:200px;width:200px;margin-top:-51px}.info-popup{background:linear-gradient(.45turn,#efefef,#fff);max-width:394px;height:280px;width:400px;max-height:280px;-webkit-box-shadow:0 5px 14px rgba(0,0,0,.25);box-shadow:0 5px 14px rgba(0,0,0,.25);overflow:hidden;border-radius:10px;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column}.info-popup_header{padding-left:15px;display:flex;height:193px;width:100%;color:#000;font-size:22px;font-weight:700;padding-top:48px;padding-right:28px;text-align:center;background:linear-gradient(102.76deg,#fbf7f7 2.32%,#e0e4e9 94.85%);background-repeat:no-repeat;background-position:center center;background-size:100% 100%}.info-popup_body{display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;font-weight:400;font-size:23px;line-height:48px;text-align:center;color:#000;padding:9px ​50px;height:89px}.info-popup_pointer-button{margin:22px auto 10px}.grey-arrow{font-family:Arial,Helvetica,sans-serif;width:253px;height:42px;line-height:42px;font-weight:700;font-size:18px;text-align:center;margin-left:50px;background-image:url(https://storage.googleapis.com/alan-public-images/rover_grey_arrow.svg);background-repeat:no-repeat;background-size:100% auto}.alan-overlay-popup__ok{background:none; opacity:0.3; color:#000}.alan-overlay-popup__ok:before{content:'✕';position: absolute;top:0;left:0;width:100%;height:100%;font-size:18px;color:#bfbfbf; opacity:1 !important}",
        html: `222<div class="info-popup"> <div class="info-popup_header" style="font-size: 21px;"><object type="image/svg+xml" class="rover-animation" data="https://storage.googleapis.com/alan-public-images/bottlerover-main.svg" alt="triangle with all three sides equal"/></object>Say </br><span style="font-size:19px; color:#EA1D2D; font-weight:800; display: contents;">"Find Tito\'s Vodka"</span></div><div class="info-popup_body"> <div class="info-popup_pointer-button grey-arrow">You can get free delivery!</div></div></div>`,
   })              
})          